### ISSUE TITLE
Improving Python3 support

### ISSUE THREAD

**Issue by fmauch** [taketwo/vim-ros#36]
Hi,

I've been using this plugin for a couple of years now and I just love it!

Recently I switched back to Archlinux as my main development system, also for ROS.

Unfortunately, I cannot get this plugin running in my current neovim setup, neither with the python2, nor with the python3 backend. It might be worthwhile to mention, that my ROS melodic setup on Archlinux uses python3 at most of the places...

This is not supposed to be a "Why does this not work?" issue, I would like to contribute to this myself. However, I've never done any vim-plugin development so far, any help for getting started / debugging would be nice. I didn't manage to get over the point of the following output:

```
Error detected while processing function <SNR>78_Detect[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vim' is not defined
Error detected while processing function <SNR>78_Detect[2]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'package' is not defined
```

For testing purposes I removed all other plugins from my config, so I am pretty sure that the error comes from this plugin, but I can't figure out where to start looking. First of all, I have no idea, what this ` <SNR>78_Detect[1]..provider#python3#Call:` means and second of all I have no idea where that `line 18` references to. `name 'vim' not defined` doesn't sound too good, though.

Looking at my `pynvim` module I  can only find a name `Nvim` which seems to have the functions available used inside `ros.vim`. My assumption is that, [this line](https://github.com/taketwo/vim-ros/blob/py3/plugin/ros.vim#L94) is causing the start of trouble. If I change it to 

```
exec g:_rpy "from pynvim import Nvim as vim\npackage = rospkg.get_package_name(vim.eval('a:filename'))"
```

I get `TypeError: eval() missing 1 required positional argument: 'string'`. So seems I hit the right line and my assumption about the `Nvim` module was not completely wrong, but I think stabbing around like this won't get me too far without having an idea what I am actually doing. If you have any hints where I could start, that would be very nice :-)

I think, python3 support would be really beneficial, especially with noetic round the corner... 

I have the following versions running:
 - Neovim v0.4.3
 - pynvim 0.4.1 (python3 version)

**Comment by taketwo** [comment]
Hi, sorry for the delay. I will probably have time today to check this out. Do you have any updates/new infos in the meantime?

**Comment by fmauch** [comment]
I don't consider 6 days on an issue much of a delay. It often takes me longer to respond.

Unfortunately I don't have any updates currently, as I had quite a busy week. In fact I deactivated the plugin completely for the time being and I already miss it :-(

**Comment by taketwo** [comment]
Please run `:checkhealth` in Nvim and post the sections about Python2/3 providers.

**Comment by taketwo** [comment]
Could you try to revert your change and instead add

```viml
exec g:_rpy "import vim"
```

after line 30 here:

https://github.com/taketwo/vim-ros/blob/61aa22baff434d2bebe2366809457202d7e996c7/plugin/ros.vim#L29-L33

**Comment by fmauch** [comment]
`healthcheck` is quite interesting... I currently don't have a python2 provider installed, this is expected.

```

health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - OK: General viewer should work properly!
  - WARNING: |g:vimtex_compiler_progname| (`nvr`) is not executable!

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: xterm-256color
  - INFO: default-terminal: tmux-256color
  - ERROR: $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
    - ADVICE:
      - $TERM may have been set by some rc (.bashrc, .zshrc, ...).

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.2
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.2.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

```

**Comment by fmauch** [comment]
With your suggested change (ontop of the py3 branch) I get the following error when starting:

```
Error detected while processing function <SNR>79_Detect[2]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(return):Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/rosvim/__init__.py", line 10, in <module>
    from . import filetypes as ft
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/rosvim/filetypes/__init__.py", line 11, in <module>
    from . import launch
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/rosvim/filetypes/launch.py", line 106, in <module>
    def goto_file():
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/vimp/functions.py", line 44, in decorator
    _functions[function_name] = f if is_function else f()
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/rosvim/filetypes/launch.py", line 108, in goto_file
    tag = pxp.get_inner_tag(vim.current.buffer, vimp.buf.cursor)
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/util/partial_xml_parser.py", line 83, in get_inner_tag
    return Tag(_between(lines, so, ec))
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/util/partial_xml_parser.py", line 12, in _between
    if s.line == e.line:
AttributeError: 'NoneType' object has no attribute 'line'
```

That looks new to me and it looks a bit clearer :-)

**Comment by taketwo** [comment]
Are you sure about C++ file? Looks more like you were opening a launch file here.

**Comment by fmauch** [comment]
I was wondering, as well. But if I open a launch file it looks different:

The output above was created by `rosed ur_robot_driver ur_driver.cpp`

If I open a launch file (`rosed ur_robot_driver ur10_bringup.launch`) I get the following
```
Error detected while processing function <SNR>79_Detect[2]..provider#python3#Call:                                                                                                                                                                                                                                                                                        
line   18:                                                                                                                                                                                                                                                                                                                                                                
Error invoking 'python_execute' on channel 3 (python3-script-host):                                                                                                                                                                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                        
  File "<string>", line 1, in <module>                                                                                                                                                                                                                                                                                                                                    
  File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 287, in command                                                                                                                                                                                                                                                                                        
    return self.request('nvim_command', string, **kwargs)                                                                                                                                                                                                                                                                                                                 
  File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request                                                                                                                                                                                                                                                                                        
    res = self._session.request(name, *args, **kwargs)                                                                                                                                                                                                                                                                                                                    
  File "/usr/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request                                                                                                                                                                                                                                                                             
    raise self.error_wrapper(err)                                                                                                                                                                                                                                                                                                                                         
pynvim.api.common.NvimError: Vim(return):Error invoking 'python_execute' on channel 3 (python3-script-host):                                                                                                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                        
  File "<string>", line 1, in <module>                                                                                                                                                                                                                                                                                                                                    
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/rosvim/__init__.py", line 10, in <module>                                                                                                                                                                                                                                                                         
    from . import filetypes as ft                                                                                                                                                                                                                                                                                                                                         
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/rosvim/filetypes/__init__.py", line 15, in <module>                                                                                                                                                                                                                                                               
    from . import manifest                                                                                                                                                                                                                                                                                                                                                
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/rosvim/filetypes/manifest.py", line 8, in <module>                                                                                                                                                                                                                                                                
    def complete(findstart, base):                                                                                                                                                                                                                                                                                                                                        
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/vimp/functions.py", line 44, in decorator                                                                                                                                                                                                                                                                         
    _functions[function_name] = f if is_function else f()                                                                                                                                                                                                                                                                                                                 
TypeError: complete() missing 2 required positional arguments: 'findstart' and 'base'
```

**Comment by taketwo** [comment]
Debugging code that one wrote 6 years ago without even running it is fun :laughing: 

OK, I think I found the problem. This code does not work correctly in Python 3:

https://github.com/taketwo/vim-ros/blob/61aa22baff434d2bebe2366809457202d7e996c7/plugin/vimp/functions.py#L31-L46

I don't have an environment to test this at the moment, so you'll have to modify and test it yourself. What needs to be changed:

* instead of testing if `f` is a function in line 33, test whether it is a class [see this](https://stackoverflow.com/a/395782/1525865)
* in line 34 `f.__name__` is defined for both functions and classes, so no need in `if` condition

**Comment by fmauch** [comment]
Alright, we're making progress here:

```
Error detected while processing function <SNR>79_Detect[2]..provider#python3#Call:                                                                                                                                                                                                                                                                                        
line   18:                                                                                                                                                                                                                                                                                                                                                                
Error invoking 'python_execute' on channel 3 (python3-script-host):                                                                                                                                                                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                        
  File "<string>", line 1, in <module>                                                                                                                                                                                                                                                                                                                                    
  File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 287, in command                                                                                                                                                                                                                                                                                        
    return self.request('nvim_command', string, **kwargs)                                                                                                                                                                                                                                                                                                                 
  File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request                                                                                                                                                                                                                                                                                        
    res = self._session.request(name, *args, **kwargs)                                                                                                                                                                                                                                                                                                                    
  File "/usr/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request                                                                                                                                                                                                                                                                             
    raise self.error_wrapper(err)                                                                                                                                                                                                                                                                                                                                         
pynvim.api.common.NvimError: Vim(return):Error invoking 'python_execute' on channel 3 (python3-script-host):                                                                                                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                        
  File "<string>", line 1, in <module>                                                                                                                                                                                                                                                                                                                                    
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/rosvim/__init__.py", line 10, in <module>                                                                                                                                                                                                                                                                         
    from . import filetypes as ft                                                                                                                                                                                                                                                                                                                                         
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/rosvim/filetypes/__init__.py", line 8, in <module>                                                                                                                                                                                                                                                                
    from . import msg                                                                                                                                                                                                                                                                                                                                                     
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/rosvim/filetypes/msg.py", line 34, in <module>                                                                                                                                                                                                                                                                    
    def goto_definition():                                                                                                                                                                                                                                                                                                                                                
  File "/home/mauch/.config/nvim/plugged/vim-ros/plugin/vimp/functions.py", line 44, in decorator                                                                                                                                                                                                                                                                         
    vim.command(proto.format(function_name))                                                                                                                                                                                                                                                                                                                              
  File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 287, in command                                                                                                                                                                                                                                                                                        
    return self.request('nvim_command', string, **kwargs)                                                                                                                                                                                                                                                                                                                 
  File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request                                                                                                                                                                                                                                                                                        
    res = self._session.request(name, *args, **kwargs)                                                                                                                                                                                                                                                                                                                    
  File "/usr/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request                                                                                                                                                                                                                                                                             
    raise self.error_wrapper(err)                                                                                                                                                                                                                                                                                                                                         
pynvim.api.common.NvimError: Vim(function):E128: Function name must start with a capital or "s:": goto_definition(...)                                                                                                                                                                                                                                                    
  exec g:_rpy "args = vimp.var['a:000']"                                                                                                                                                                                                                                                                                                                                  
  exec g:_rpy "rv = vimp.functions._functions['goto_definition'](*args)"                                                                                                                                                                                                                                                                                                  
  exec g:_rpy "vim.command('return ' + vimp.escape(rv))"                                                                                                                                                                                                                                                                                                                  
endfunction
```

If I understand that correctly, nvim API changed that hey require a certain naming scheme?

**Comment by taketwo** [comment]
Did you remove `name or` part in this condition? Please don't!

```python
         function_name = name or (f.func_name if is_function else f.__name__) 
```

**Comment by fmauch** [comment]
I see :-) sorry, I misunderstood you there.

**Comment by fmauch** [comment]
You can see my changes in the draft PR.

with the changes from that, we are back at https://github.com/taketwo/vim-ros/issues/36#issuecomment-625283878

**Comment by taketwo** [comment]
Please see my inline comments in the draft PR, you forgot a `not` :)

**Comment by fmauch** [comment]
Stupid me. Now I also understand the change. It wasn't clear to me that we want to find out whether it's a function or a class. I should have read the code more thoroughly...

**Comment by fmauch** [comment]
But it seems to work currently. I'll try to play around a bit more and then clean up the MR and remove the draft tag. Thanks for your huge support!

**Comment by taketwo** [comment]
> It wasn't clear to me that we want to find out whether it's a function or a class.

Yeah. And in case it's a class, we want to instantiate it with `f()` syntax. However, if we made a mistake determining whether it's a class or a function, instead of object instantiation `f()` does a function call. So every `vimp.function` decorator application in the plugin actually called the decorated function. This lead to these seemingly random errors in various unrelated places.
